### ISSUE TITLE
SPI port 1

### ISSUE THREAD

**Issue by ToninoTarsi** [ladecadence/pyRF95#2]
Hi and thanks for your work.

I think I will use your library in my Meteo Station project but I need to use SPI port 1 there so I did this modification :

https://github.com/ladecadence/pyRF95/compare/master...ToninoTarsi:master

If you think is useful I can ask for a merge.

Question :

Could MAX_MESSAGE_LEN be increased or it is something related with LoRA ?

Thanks

**Comment by ladecadence** [comment]
Yes please, let's merge the changes.
And also yes, the 255 bytes limit is defined in the LoRa protocol (not counting LoRaWan headers if you use them).

**Comment by ToninoTarsi** [comment]
Ok ... I'm just waiting for my RFM95 and when tested  I will ask for a push request.
Thanks
